# Generated by Django 4.0.6 on 2022-07-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='explanation',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
