# Generated by Django 4.0.6 on 2022-07-16 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='origin',
            new_name='originss',
        ),
    ]
