# Generated by Django 4.0.6 on 2022-07-16 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_origin_product_originss'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.origin'),
            preserve_default=False,
        ),
    ]
