# Generated by Django 4.0.6 on 2022-07-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='origin',
            old_name='country',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='originss',
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(max_length=100),
        ),
    ]
