# Generated by Django 4.0.6 on 2022-07-17 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_country_origin_name_remove_product_originss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.origin'),
        ),
    ]
